SELECT
  /* Core indicators */
  (SELECT SUM(HIRE_REVENUE)  FROM FACT_HIRE_AGG)                           AS TOTAL_HIRE_REVENUE,
  (SELECT SUM(SALES_REVENUE) FROM FACT_SALES_AGG)                          AS TOTAL_SALES_REVENUE,
  (SELECT SUM(UNITS_HIRED)   FROM FACT_HIRE_AGG)                           AS NUM_EQUIP_HIRED,
  (SELECT SUM(UNITS_SOLD)    FROM FACT_SALES_AGG)                          AS NUM_EQUIP_SOLD,
  (SELECT SUM(HIRE_REVENUE)/NULLIF(SUM(HIRE_COUNT),0)  FROM FACT_HIRE_AGG) AS AVG_HIRE_REV_PER_TXN,
  (SELECT SUM(SALES_REVENUE)/NULLIF(SUM(SALES_COUNT),0) FROM FACT_SALES_AGG) AS AVG_SALE_REV_PER_TXN
FROM DUAL;
-- monthly trend of core indicators
WITH H AS (
  SELECT MONTH_ID,
         SUM(HIRE_REVENUE) AS HIRE_REV,
         SUM(HIRE_COUNT)   AS HIRE_TXN,
         SUM(UNITS_HIRED)  AS UNITS_HIRED
  FROM FACT_HIRE_AGG GROUP BY MONTH_ID
),
S AS (
  SELECT MONTH_ID,
         SUM(SALES_REVENUE) AS SALES_REV,
         SUM(SALES_COUNT)   AS SALES_TXN,
         SUM(UNITS_SOLD)    AS UNITS_SOLD
  FROM FACT_SALES_AGG GROUP BY MONTH_ID
)
SELECT m.MONTH_ID, m.YEAR, m.SEASON,
       NVL(H.HIRE_REV,0)  AS HIRE_REVENUE,
       CASE WHEN NVL(H.HIRE_TXN,0)=0  THEN NULL ELSE ROUND(H.HIRE_REV/H.HIRE_TXN,2) END AS AVG_HIRE_REV_PER_TXN,
       NVL(H.UNITS_HIRED,0) AS NUM_EQUIP_HIRED,
       NVL(S.SALES_REV,0) AS SALES_REVENUE,
       CASE WHEN NVL(S.SALES_TXN,0)=0 THEN NULL ELSE ROUND(S.SALES_REV/S.SALES_TXN,2) END AS AVG_SALE_REV_PER_TXN,
       NVL(S.UNITS_SOLD,0)  AS NUM_EQUIP_SOLD
FROM DIM_MONTH m
LEFT JOIN H ON H.MONTH_ID=m.MONTH_ID
LEFT JOIN S ON S.MONTH_ID=m.MONTH_ID
WHERE m.MONTH_ID BETWEEN 201804 AND 202012
ORDER BY m.MONTH_ID;

--seasonal trend of core indicators
WITH H AS (
  SELECT m.SEASON,
         SUM(f.HIRE_REVENUE) AS HIRE_REV,
         SUM(f.HIRE_COUNT)   AS HIRE_TXN,
         SUM(f.UNITS_HIRED)  AS UNITS_HIRED
  FROM FACT_HIRE_AGG f JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
  GROUP BY m.SEASON
),
S AS (
  SELECT m.SEASON,
         SUM(f.SALES_REVENUE) AS SALES_REV,
         SUM(f.SALES_COUNT)   AS SALES_TXN,
         SUM(f.UNITS_SOLD)    AS UNITS_SOLD
  FROM FACT_SALES_AGG f JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
  GROUP BY m.SEASON
)
SELECT SEASON,                                        -- ✅ no H./S. qualifier
       NVL(H.HIRE_REV,0)  AS HIRE_REVENUE,
       CASE WHEN NVL(H.HIRE_TXN,0)=0  THEN NULL ELSE ROUND(H.HIRE_REV/H.HIRE_TXN,2) END AS AVG_HIRE_REV_PER_TXN,
       NVL(H.UNITS_HIRED,0) AS NUM_EQUIP_HIRED,
       NVL(S.SALES_REV,0) AS SALES_REVENUE,
       CASE WHEN NVL(S.SALES_TXN,0)=0 THEN NULL ELSE ROUND(S.SALES_REV/S.SALES_TXN,2) END AS AVG_SALE_REV_PER_TXN,
       NVL(S.UNITS_SOLD,0)  AS NUM_EQUIP_SOLD,
       ROUND(100 * RATIO_TO_REPORT(NVL(H.HIRE_REV,0)+NVL(S.SALES_REV,0)) OVER (), 1) AS TOTAL_REV_SHARE_PCT
FROM H FULL OUTER JOIN S USING (SEASON)               -- ✅ USING is fine
ORDER BY SEASON;


--branch performance of core indicators
WITH H AS (
  SELECT COMPANY_BRANCH, SUM(HIRE_REVENUE) AS HIRE_REV, SUM(HIRE_COUNT) AS HIRE_TXN
  FROM FACT_HIRE_AGG GROUP BY COMPANY_BRANCH
),
S AS (
  SELECT COMPANY_BRANCH, SUM(SALES_REVENUE) AS SALES_REV, SUM(SALES_COUNT) AS SALES_TXN
  FROM FACT_SALES_AGG GROUP BY COMPANY_BRANCH
)
SELECT COMPANY_BRANCH,                                 -- ✅ no H./S. qualifier
       NVL(H.HIRE_REV,0)  AS HIRE_REVENUE,
       NVL(S.SALES_REV,0) AS SALES_REVENUE,
       NVL(H.HIRE_REV,0) + NVL(S.SALES_REV,0) AS TOTAL_REVENUE,
       CASE WHEN NVL(H.HIRE_TXN,0)=0  THEN NULL ELSE ROUND(H.HIRE_REV/H.HIRE_TXN,2) END AS AVG_HIRE_REV_PER_TXN,
       CASE WHEN NVL(S.SALES_TXN,0)=0 THEN NULL ELSE ROUND(S.SALES_REV/S.SALES_TXN,2) END AS AVG_SALE_REV_PER_TXN
FROM H FULL OUTER JOIN S USING (COMPANY_BRANCH)
ORDER BY TOTAL_REVENUE DESC;


--category performance of core indicators
WITH H AS (
  SELECT CATEGORY_ID,
         SUM(HIRE_REVENUE) AS HIRE_REV,
         SUM(HIRE_COUNT)   AS HIRE_TXN,
         SUM(UNITS_HIRED)  AS UNITS_HIRED
  FROM FACT_HIRE_AGG GROUP BY CATEGORY_ID
),
S AS (
  SELECT CATEGORY_ID,
         SUM(SALES_REVENUE) AS SALES_REV,
         SUM(SALES_COUNT)   AS SALES_TXN,
         SUM(UNITS_SOLD)    AS UNITS_SOLD
  FROM FACT_SALES_AGG GROUP BY CATEGORY_ID
)
SELECT c.CATEGORY_ID, c.CATEGORY_DESCRIPTION,
       NVL(H.HIRE_REV,0)  AS HIRE_REVENUE,
       CASE WHEN NVL(H.HIRE_TXN,0)=0  THEN NULL ELSE ROUND(H.HIRE_REV/H.HIRE_TXN,2) END AS AVG_HIRE_REV_PER_TXN,
       NVL(H.UNITS_HIRED,0) AS NUM_EQUIP_HIRED,
       NVL(S.SALES_REV,0) AS SALES_REVENUE,
       CASE WHEN NVL(S.SALES_TXN,0)=0 THEN NULL ELSE ROUND(S.SALES_REV/S.SALES_TXN,2) END AS AVG_SALE_REV_PER_TXN,
       NVL(S.UNITS_SOLD,0)  AS NUM_EQUIP_SOLD,
       ROUND(100 * RATIO_TO_REPORT(NVL(H.HIRE_REV,0)+NVL(S.SALES_REV,0)) OVER (),1) AS TOTAL_REV_SHARE_PCT
FROM DIM_CATEGORY c
LEFT JOIN H ON H.CATEGORY_ID=c.CATEGORY_ID
LEFT JOIN S ON S.CATEGORY_ID=c.CATEGORY_ID
ORDER BY TOTAL_REV_SHARE_PCT DESC;

--customer performance of core indicators
WITH H AS (
  SELECT CUSTOMER_TYPE_ID,
         SUM(HIRE_REVENUE) AS HIRE_REV,
         SUM(HIRE_COUNT)   AS HIRE_TXN,
         SUM(UNITS_HIRED)  AS UNITS_HIRED
  FROM FACT_HIRE_AGG GROUP BY CUSTOMER_TYPE_ID
),
S AS (
  SELECT CUSTOMER_TYPE_ID,
         SUM(SALES_REVENUE) AS SALES_REV,
         SUM(SALES_COUNT)   AS SALES_TXN,
         SUM(UNITS_SOLD)    AS UNITS_SOLD
  FROM FACT_SALES_AGG GROUP BY CUSTOMER_TYPE_ID
)
SELECT t.CUSTOMER_TYPE_ID, t.DESCRIPTION AS CUSTOMER_TYPE,
       NVL(H.HIRE_REV,0)  AS HIRE_REVENUE,
       CASE WHEN NVL(H.HIRE_TXN,0)=0  THEN NULL ELSE ROUND(H.HIRE_REV/H.HIRE_TXN,2) END AS AVG_HIRE_REV_PER_TXN,
       NVL(H.UNITS_HIRED,0) AS NUM_EQUIP_HIRED,
       NVL(S.SALES_REV,0) AS SALES_REVENUE,
       CASE WHEN NVL(S.SALES_TXN,0)=0 THEN NULL ELSE ROUND(S.SALES_REV/S.SALES_TXN,2) END AS AVG_SALE_REV_PER_TXN,
       NVL(S.UNITS_SOLD,0)  AS NUM_EQUIP_SOLD
FROM DIM_CUSTOMER_TYPE t
LEFT JOIN H ON H.CUSTOMER_TYPE_ID=t.CUSTOMER_TYPE_ID
LEFT JOIN S ON S.CUSTOMER_TYPE_ID=t.CUSTOMER_TYPE_ID
ORDER BY CUSTOMER_TYPE;

--sales scale
SELECT PRICE_SCALE,
       SUM(SALES_REVENUE) AS SALES_REVENUE,
       SUM(SALES_COUNT)   AS SALES_TXN,
       ROUND(SUM(SALES_REVENUE)/NULLIF(SUM(SALES_COUNT),0),2) AS AVG_SALE_REV_PER_TXN,
       ROUND(100 * RATIO_TO_REPORT(SUM(SALES_REVENUE)) OVER (),1) AS REV_SHARE_PCT
FROM FACT_SALES_AGG
GROUP BY PRICE_SCALE
ORDER BY DECODE(PRICE_SCALE,'LOW',1,'MED',2,'HIGH',3,99);

--year
WITH T AS (
  SELECT m.YEAR,
         SUM(f.HIRE_REVENUE)  AS HIRE_REV,
         0                    AS SALES_REV
  FROM FACT_HIRE_AGG f JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
  GROUP BY m.YEAR
  UNION ALL
  SELECT m.YEAR,
         0,
         SUM(f.SALES_REVENUE)
  FROM FACT_SALES_AGG f JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
  GROUP BY m.YEAR
),
Y AS (
  SELECT YEAR,
         SUM(HIRE_REV)  AS HIRE_REV,
         SUM(SALES_REV) AS SALES_REV,
         SUM(HIRE_REV)+SUM(SALES_REV) AS TOTAL_REV
  FROM T GROUP BY YEAR
)
SELECT YEAR,
       HIRE_REV, SALES_REV, TOTAL_REV,
       (TOTAL_REV - LAG(TOTAL_REV) OVER (ORDER BY YEAR)) AS YOY_CHANGE,
       ROUND(100 * (TOTAL_REV / NULLIF(LAG(TOTAL_REV) OVER (ORDER BY YEAR),0) - 1),1) AS YOY_GROWTH_PCT
FROM Y
ORDER BY YEAR;

--self defined
select count(*) from FACT_SALES_AGG where price_scale = 'HIGH' and MONTH_ID like '2020%';
select count(*) from FACT_SALES_AGG where MONTH_ID like '2020%';
select * from FACT_hire_AGG;
select sum(units_sold) from FACT_SALES_AGG where MONTH_ID like '2020%';
select sum(units_hired) from FACT_HIRE_AGG where MONTH_ID like '2020%';
select * from hire;