SELECT * FROM ADDRESS;
SELECT * FROM CATEGORY;
SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_TYPE;
SELECT * FROM EQUIPMENT;    
SELECT * FROM HIRE;
SELECT * FROM SALES;
SELECT * FROM STAFF;
--drop tables if exist
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_SALES_TXN_WITH_SCALE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'FACT_SALES_AGG','FACT_HIRE_AGG',
      'DIM_MONTH','DIM_CATEGORY','DIM_BRANCH',
      'DIM_CUSTOMER_TYPE','DIM_PRICE_SCALE'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
END;
/
--month dim
drop table dim_month;
CREATE TABLE DIM_MONTH AS
SELECT DISTINCT
  TO_NUMBER(TO_CHAR(TRUNC(d,'MM'),'YYYYMM')) AS MONTH_ID,
  TO_NUMBER(TO_CHAR(d,'YYYY'))               AS YEAR,
  CASE
    WHEN TO_NUMBER(TO_CHAR(d,'MM')) BETWEEN 9 AND 11 THEN 'Spring'
    WHEN TO_NUMBER(TO_CHAR(d,'MM')) IN (12,1,2)      THEN 'Summer'
    WHEN TO_NUMBER(TO_CHAR(d,'MM')) BETWEEN 3 AND 5  THEN 'Autumn'
    ELSE 'Winter'
  END AS SEASON
FROM (
  SELECT TRUNC(SALES_DATE) d FROM SALES
  UNION SELECT TRUNC(START_DATE) FROM HIRE
--   UNION SELECT TRUNC(END_DATE)   FROM HIRE as we say only consider the start date
);
ALTER TABLE DIM_MONTH ADD CONSTRAINT PK_DIM_MONTH PRIMARY KEY (MONTH_ID);

SELECT * FROM DIM_MONTH;

--category dim
drop table dim_category;

CREATE TABLE DIM_CATEGORY AS
SELECT DISTINCT
  c.CATEGORY_ID,
  TRIM(c.CATEGORY_DESCRIPTION) AS CATEGORY_DESCRIPTION
FROM CATEGORY c;
ALTER TABLE DIM_CATEGORY ADD CONSTRAINT PK_DIM_CATEGORY PRIMARY KEY (CATEGORY_ID);

SELECT * FROM DIM_CATEGORY;

--branch dim
drop table dim_branch;

CREATE TABLE DIM_BRANCH AS
SELECT DISTINCT
  UPPER(TRIM(COMPANY_BRANCH)) AS COMPANY_BRANCH
FROM STAFF
WHERE COMPANY_BRANCH IS NOT NULL;

ALTER TABLE DIM_BRANCH ADD CONSTRAINT PK_DIM_BRANCH PRIMARY KEY (COMPANY_BRANCH);

SELECT * FROM DIM_BRANCH;

--customer type dim
drop table dim_customer_type;
CREATE TABLE DIM_CUSTOMER_TYPE AS
SELECT DISTINCT
  ct.CUSTOMER_TYPE_ID,
  TRIM(ct.DESCRIPTION) AS DESCRIPTION
FROM CUSTOMER_TYPE ct;
ALTER TABLE DIM_CUSTOMER_TYPE ADD CONSTRAINT PK_DIM_CUSTTYPE PRIMARY KEY (CUSTOMER_TYPE_ID);
SELECT * FROM DIM_CUSTOMER_TYPE;

--price scale dim
drop table dim_price_scale;
CREATE TABLE DIM_PRICE_SCALE (
  PRICE_SCALE VARCHAR2(10) PRIMARY KEY,
  SCALE_DESC  VARCHAR2(100)
);

INSERT INTO DIM_PRICE_SCALE VALUES ('LOW',  'Total sales price < 5,000');
INSERT INTO DIM_PRICE_SCALE VALUES ('MED',  'Total sales price 5,000–10,000');
INSERT INTO DIM_PRICE_SCALE VALUES ('HIGH', 'Total sales price > 10,000');
COMMIT;
SELECT * FROM DIM_PRICE_SCALE;

--sales fact
CREATE OR REPLACE VIEW V_SALES_TXN_WITH_SCALE AS
SELECT s.*,
       CASE
         WHEN s.TOTAL_SALES_PRICE <  5000  THEN 'LOW'
         WHEN s.TOTAL_SALES_PRICE <= 10000 THEN 'MED'
         ELSE 'HIGH'
       END AS PRICE_SCALE
FROM SALES s
WHERE s.TOTAL_SALES_PRICE > 0;   -- assume cleaned of invalid/negative

CREATE TABLE FACT_SALES_AGG AS
SELECT
  TO_NUMBER(TO_CHAR(TRUNC(s.SALES_DATE,'MM'),'YYYYMM')) AS MONTH_ID,
  UPPER(TRIM(st.COMPANY_BRANCH))                        AS COMPANY_BRANCH,
  e.CATEGORY_ID,
  cu.CUSTOMER_TYPE_ID,
  v.PRICE_SCALE,
  SUM(s.TOTAL_SALES_PRICE)                              AS SALES_REVENUE,
  SUM(s.QUANTITY)                                       AS UNITS_SOLD,
  COUNT(*)                                              AS SALES_COUNT
FROM V_SALES_TXN_WITH_SCALE v
JOIN SALES s          ON s.SALES_ID     = v.SALES_ID
JOIN EQUIPMENT e      ON e.EQUIPMENT_ID = s.EQUIPMENT_ID
JOIN CUSTOMER cu      ON cu.CUSTOMER_ID = s.CUSTOMER_ID
JOIN STAFF st         ON st.STAFF_ID    = s.STAFF_ID
GROUP BY
  TO_NUMBER(TO_CHAR(TRUNC(s.SALES_DATE,'MM'),'YYYYMM')),
  UPPER(TRIM(st.COMPANY_BRANCH)),
  e.CATEGORY_ID,
  cu.CUSTOMER_TYPE_ID,
  v.PRICE_SCALE;

SELECT * FROM FACT_SALES_AGG;

--hire fact
CREATE TABLE FACT_HIRE_AGG AS
SELECT
  TO_NUMBER(TO_CHAR(TRUNC(h.START_DATE,'MM'),'YYYYMM')) AS MONTH_ID,
  UPPER(TRIM(st.COMPANY_BRANCH))                        AS COMPANY_BRANCH,
  e.CATEGORY_ID,
  cu.CUSTOMER_TYPE_ID,
  SUM(h.TOTAL_HIRE_PRICE)                               AS HIRE_REVENUE,
  SUM(h.QUANTITY)                                       AS UNITS_HIRED,
  COUNT(*)                                              AS HIRE_COUNT
FROM HIRE h
JOIN EQUIPMENT e ON e.EQUIPMENT_ID = h.EQUIPMENT_ID
JOIN CUSTOMER cu ON cu.CUSTOMER_ID = h.CUSTOMER_ID
JOIN STAFF st    ON st.STAFF_ID    = h.STAFF_ID
WHERE h.TOTAL_HIRE_PRICE > 0
GROUP BY
  TO_NUMBER(TO_CHAR(TRUNC(h.START_DATE,'MM'),'YYYYMM')),
  UPPER(TRIM(st.COMPANY_BRANCH)),
  e.CATEGORY_ID,
  cu.CUSTOMER_TYPE_ID;
SELECT * FROM FACT_HIRE_AGG;

--add foreign keys
ALTER TABLE FACT_SALES_AGG
  ADD CONSTRAINT FK_FSA_MONTH   FOREIGN KEY (MONTH_ID)         REFERENCES DIM_MONTH(MONTH_ID);
ALTER TABLE FACT_SALES_AGG
  ADD CONSTRAINT FK_FSA_BRANCH  FOREIGN KEY (COMPANY_BRANCH)   REFERENCES DIM_BRANCH(COMPANY_BRANCH);
ALTER TABLE FACT_SALES_AGG
  ADD CONSTRAINT FK_FSA_CAT     FOREIGN KEY (CATEGORY_ID)      REFERENCES DIM_CATEGORY(CATEGORY_ID);
ALTER TABLE FACT_SALES_AGG
  ADD CONSTRAINT FK_FSA_CTYPE   FOREIGN KEY (CUSTOMER_TYPE_ID) REFERENCES DIM_CUSTOMER_TYPE(CUSTOMER_TYPE_ID);
ALTER TABLE FACT_SALES_AGG
  ADD CONSTRAINT FK_FSA_SCALE   FOREIGN KEY (PRICE_SCALE)      REFERENCES DIM_PRICE_SCALE(PRICE_SCALE);

ALTER TABLE FACT_HIRE_AGG
  ADD CONSTRAINT FK_FHA_MONTH   FOREIGN KEY (MONTH_ID)         REFERENCES DIM_MONTH(MONTH_ID);
ALTER TABLE FACT_HIRE_AGG
  ADD CONSTRAINT FK_FHA_BRANCH  FOREIGN KEY (COMPANY_BRANCH)   REFERENCES DIM_BRANCH(COMPANY_BRANCH);
ALTER TABLE FACT_HIRE_AGG
  ADD CONSTRAINT FK_FHA_CAT     FOREIGN KEY (CATEGORY_ID)      REFERENCES DIM_CATEGORY(CATEGORY_ID);
ALTER TABLE FACT_HIRE_AGG
  ADD CONSTRAINT FK_FHA_CTYPE   FOREIGN KEY (CUSTOMER_TYPE_ID) REFERENCES DIM_CUSTOMER_TYPE(CUSTOMER_TYPE_ID);
COMMIT;

--structure check
-- Column layouts
SELECT table_name, column_name, data_type, data_length
FROM user_tab_columns
WHERE table_name IN ('DIM_MONTH','DIM_CATEGORY','DIM_BRANCH','DIM_CUSTOMER_TYPE','DIM_PRICE_SCALE',
                     'FACT_SALES_AGG','FACT_HIRE_AGG')
ORDER BY table_name, column_id;

-- Row counts
SELECT 'DIM_MONTH' tbl, COUNT(*) cnt FROM DIM_MONTH UNION ALL
SELECT 'DIM_CATEGORY', COUNT(*) FROM DIM_CATEGORY UNION ALL
SELECT 'DIM_BRANCH', COUNT(*) FROM DIM_BRANCH UNION ALL
SELECT 'DIM_CUSTOMER_TYPE', COUNT(*) FROM DIM_CUSTOMER_TYPE UNION ALL
SELECT 'DIM_PRICE_SCALE', COUNT(*) FROM DIM_PRICE_SCALE UNION ALL
SELECT 'FACT_SALES_AGG', COUNT(*) FROM FACT_SALES_AGG UNION ALL
SELECT 'FACT_HIRE_AGG', COUNT(*) FROM FACT_HIRE_AGG;

--sample answers to sample queries
-- Total sales revenue in January 2020=356600
SELECT SUM(SALES_REVENUE) AS TOTAL_SALES_JAN2020
FROM FACT_SALES_AGG f
JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
WHERE m.YEAR=2020 AND f.MONTH_ID=202001;

-- How many pieces of equipment were sold in Winter 2018?=44
SELECT SUM(UNITS_SOLD) AS UNITS_SOLD_WINTER2018
FROM FACT_SALES_AGG f
JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
WHERE m.YEAR=2018 AND m.SEASON='Winter';

-- How many equipments was hired by business customers? 320
SELECT SUM(UNITS_HIRED) AS UNITS_HIRED_BUSINESS
FROM FACT_HIRE_AGG f
JOIN DIM_CUSTOMER_TYPE t ON t.CUSTOMER_TYPE_ID=f.CUSTOMER_TYPE_ID
WHERE UPPER(t.DESCRIPTION) LIKE '%BUSINESS%';

-- Total hire revenue in Clayton branch =47670
SELECT SUM(HIRE_REVENUE) AS HIRE_REV_CLAYTON
FROM FACT_HIRE_AGG
WHERE COMPANY_BRANCH='CLAYTON';

-- How many trailers were hired by individual customers in Summer? =6
SELECT SUM(UNITS_HIRED) AS TRAILERS_HIRED
FROM FACT_HIRE_AGG f
JOIN DIM_MONTH m    ON m.MONTH_ID=f.MONTH_ID
JOIN DIM_CATEGORY c ON c.CATEGORY_ID=f.CATEGORY_ID
JOIN DIM_CUSTOMER_TYPE t ON t.CUSTOMER_TYPE_ID=f.CUSTOMER_TYPE_ID
WHERE m.SEASON='Summer'
  AND UPPER(c.CATEGORY_DESCRIPTION)='TRAILERS'
  AND UPPER(t.DESCRIPTION) LIKE '%INDIVIDUAL%';

-- Average sale revenue for Lighting in 2019 (per transaction) =28000
SELECT SUM(SALES_REVENUE)/NULLIF(SUM(SALES_COUNT),0) AS AVG_SALE_2019_LIGHTING
FROM FACT_SALES_AGG f
JOIN DIM_MONTH m    ON m.MONTH_ID=f.MONTH_ID
JOIN DIM_CATEGORY c ON c.CATEGORY_ID=f.CATEGORY_ID
WHERE m.YEAR=2019 AND UPPER(c.CATEGORY_DESCRIPTION)='LIGHTING';
select * from sales WHERE equipment_id IN (SELECT equipment_id FROM equipment WHERE category_id = 8);

-- Average hire revenue for Vehicles by individual customers (per transaction) =1866
SELECT SUM(HIRE_REVENUE)/NULLIF(SUM(HIRE_COUNT),0) AS AVG_HIRE_VEH_INDIV
FROM FACT_HIRE_AGG f
JOIN DIM_CATEGORY c ON c.CATEGORY_ID=f.CATEGORY_ID
JOIN DIM_CUSTOMER_TYPE t ON t.CUSTOMER_TYPE_ID=f.CUSTOMER_TYPE_ID
WHERE UPPER(c.CATEGORY_DESCRIPTION)='VEHICLES'
  AND UPPER(t.DESCRIPTION) LIKE '%INDIVIDUAL%';
select * from HIRE WHERE equipment_id IN (SELECT equipment_id FROM equipment WHERE category_id = 14);

-- How much sales revenue was generated from a HIGH sale in Summer?=2505700
SELECT SUM(SALES_REVENUE) AS SUM_HIGH_SALES_SUMMER
FROM FACT_SALES_AGG f
JOIN DIM_MONTH m ON m.MONTH_ID=f.MONTH_ID
WHERE m.SEASON='Summer' AND f.PRICE_SCALE='HIGH';

SELECT SALES_ID, SALES_DATE, TOTAL_SALES_PRICE
FROM SALES
WHERE TOTAL_SALES_PRICE > 10000
  AND TO_CHAR(SALES_DATE,'MM') IN ('12','01','02');

